routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => ['bloqued']], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index');
	Route::get('/perfil', 'UserController@account')->name('account');
	Route::put('/perfil', 'UserController@updateAccount')->name('update_account');
	Route::get('/comprar-minutos', 'TicketController@time')->name('time');
	Route::post('/comprar-minutos', 'TicketController@buyTime')->name('buy_time');
	Route::get('/cargar-billetera', 'TicketController@showWallet')->name('wallet');
	Route::post('/cargar-billetera', 'TicketController@buyWallet')->name('buy_wallet');
	Route::get('/comprar-ticket', 'TicketController@tickets')->name('tickets');
	Route::post('/comprar-ticket', 'TicketController@buyTicket')->name('buy_tickets');
	Route::resource('/mis-vehiculos', 'VehicleController');


	Route::group(['middleware' => ['role:admin,pmt'] ], function(){
		Route::resource('multas', 'PenaltyController');
	});

	Route::group(['middleware' => 'role:admin'], function(){
		Route::resource('zonas', 'ZoneController');
		Route::resource('usuarios', 'UserController');
		Route::resource('planes', 'PlanController');
		Route::resource('metodos', 'PaymentMethodController');
	});
});

app/PaymentMethod.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PaymentMethod extends Model
{
    protected $fillable = ['title', 'url', 'status'];
}

app/Http/Controllers/PaymentMethodController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\PaymentMethod;

class PaymentMethodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $methods = PaymentMethod::paginate(15);
        return view('payment_methods.index', ['methods' => $methods]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('payment_methods.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'  => 'string|required|max:255|unique:payment_methods',
            'url'    => 'url|required|unique:payment_methods',
            'status' => 'boolean'
        ]);

        $plan = PaymentMethod::create($request->only(['title', 'url', 'status']));

        if($plan){
            flash('El metodo de pago ha sido creado!')->success();
            return redirect()->route('metodos.index');
        } else {
            flash('El metodo de pago no pudo ser creado')->danger();
            return redirect()->route('metodos.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/payment_methods/create.blade.php
@extends('layouts.app')

@section('content')

	<h3>Agregar Metodo de Pago</h3>

	{!! Form::open(['route' => 'metodos.store', 'method' => 'POST', 'role' => 'form']) !!}
		<div class="form-group">
			{!! Form::text('title', '', ['class' => 'form-control', 'placeholder' => 'Descripción'] )!!}

			@if ($errors->has('title'))
	        <span class="help-block">
	            <strong>{{ $errors->first('title') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('url', '', ['class' => 'form-control', 'placeholder' => 'URL'] )!!}

			@if ($errors->has('url'))
	        <span class="help-block">
	            <strong>{{ $errors->first('url') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			<label for="status">Estado</label>
			{!! Form::select('status', [true => 'Activo', false => 'Inactivo'], true, ['class' => 'form-control', 'id' => 'status'] )!!}
			@if ($errors->has('status'))
	        <span class="help-block">
	            <strong>{{ $errors->first('status') }}</strong>
	        </span>
	        @endif
		</div>

		<div class="form-group">
			{!! Form::submit('Guardar', ['class' => 'btn btn-success'] )!!}
			<a href="{{ route('planes.index')}}" class="btn btn-danger pull-right">Cancelar</a>
		</div>

	{!! Form::close() !!}

@endsection

resources/views/payment_methods/index.blade.php
@extends('layouts.app')

@section('content')

	<h3>Planes</h3>

	<a href="{{ route('metodos.create')}}" class="btn btn-success">Agregar Metodo de Pago</a>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Descripcion</th>
				<th>URL</th>
				<th>Estado</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			@foreach ($methods as $method)
				<tr data-id="{{ $method->id }}">
					<td>{{ $method->title }}</td>
					<td>{{ $method->url }}</td>
					<td>{{ $method->status }}</td>
					<td>
						<a href="{{ route('metodos.edit', $method->id)}}">Editar</a>
						<a href="#" class="btn-remove">Eliminar</a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>

	{!! $methods->links() !!}

	{!! Form::open(['route' => ['metodos.destroy',':ROW_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
	{!! Form::close() !!}

@endsection

@section('scripts')
<script type="text/javascript">
	$(function() {
		$('.btn-remove').click(function(e){
			e.preventDefault();
			var row = $(this).parents('tr');
			var id = row.data('id');
			swal({
			  title: "Estas seguro de eliminar el metodo de pago?",
			  text: "Con esta acción los datos no podrán ser recuperados!",
			  type: "warning",
			  showCancelButton: true,
			  confirmButtonColor: "#DD6B55",
			  confirmButtonText: "Eliminar!",
			  cancelButtonText: "Cancelar!"
			}).then(function(isConfirm){
				console.log(isConfirm);
			  if (isConfirm) {
				var form = $('#form-delete');
				var url = form.attr('action').replace(':ROW_ID',id);
				var data = form.serialize();
				var type = "";
				var title = "";
			  	$.post(url,data, function(result){
					if(result.success){
						row.fadeOut();
						type = "success";
						title = "Operación realizada!";
					}else{
						type = "error";
						title =  "No se pudo realizar la operación";
					}
					swal({   title: title,   text: result.message,   type: type,   confirmButtonText: "Aceptar" });
				}).fail(function (){
					swal('No se pudo realizar la petición.');
				});
			  } else {
			    swal("Cancelado", "El metodo de pago no ha sido eliminado", "error");
			  }
			});
		});
	});
</script>
@endsection