routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => ['bloqued']], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index');
	Route::get('/perfil', 'UserController@account')->name('account');
	Route::put('/perfil', 'UserController@updateAccount')->name('update_account');
	Route::get('/comprar-minutos', 'TicketController@time')->name('time');
	Route::post('/comprar-minutos', 'TicketController@buyTime')->name('buy_time');
	Route::get('/cargar-billetera', 'TicketController@showWallet')->name('wallet');
	Route::post('/cargar-billetera', 'TicketController@buyWallet')->name('buy_wallet');
	Route::get('/comprar-ticket', 'TicketController@tickets')->name('tickets');
	Route::post('/comprar-ticket', 'TicketController@buyTicket')->name('buy_tickets');
	Route::resource('/mis-vehiculos', 'VehicleController');


	Route::group(['middleware' => ['role:admin,pmt'] ], function(){
		Route::resource('multas', 'PenaltyController');
	});

	Route::group(['middleware' => 'role:admin'], function(){
		Route::resource('zonas', 'ZoneController');
		Route::resource('usuarios', 'UserController');
		Route::resource('planes', 'PlanController');
		Route::resource('metodos', 'PaymentMethodController');
	});
});

app/Vehicle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\User;

class Vehicle extends Model
{
    protected $fillable = ['plate', 'brand', 'color', 'model', 'chassis', 'document', 'status'];

    public function users(){
    	return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/VehicleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;

use App\Vehicle;

class VehicleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user     = Auth::user();
        $vehicles = $user->vehicles()->paginate(15);

        return view('vehicles.index', ['vehicles' => $vehicles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vehicles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'plate'    => 'required|string',
            'brand'    => 'required|string',
            'color'    => 'required|string',
            'model'    => 'required|string',
            'chassis'  => 'string',
            'document' => 'required|string',
            'status'   => 'required|integer'
        ]);

        $user = Auth::user();

        $vehicle = Vehicle::where('plate', $request->plate)->first();

        if(!$vehicle){
            $vehicle = Vehicle::create($request->only(['plate', 'brand', 'color', 'model', 'chassis', 'document', 'status']));
        }

        if($vehicle){
            $user->vehicles()->attach($vehicle);

            flash('El vehiculo ha sido creado')->success();
            return redirect()->route('mis-vehiculos.index');
        } else {
            flash('El vehiculo no pudo ser creado')->error();
            return redirect()->route('mis-vehiculos.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehicle = Vehicle::find($id);
        return view('vehicles.edit', ['vehicle' => $vehicle]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'plate'    => 'required|string',
            'brand'    => 'required|string',
            'color'    => 'required|string',
            'model'    => 'required|string',
            'chassis'  => 'string',
            'document' => 'required|string',
            'status'   => 'required|integer'
        ]);

        $vehicle = Vehicle::find($id);

        if($vehicle->update($request->only(['plate', 'brand', 'color', 'model', 'chassis', 'document', 'status']))){
            flash('El vehiculo ha sido modificado')->success();
            return redirect()->route('mis-vehiculos.index');
        } else {
            flash('El vehiculo no pudo ser modificado')->error();
            return redirect()->route('mis-vehiculos.update', $id);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user    = Auth::user();
        $vehicle = Vehicle::find($id);

        if($user->vehicles()->detach($vehicle)){
            return response()->json(['success' => true, 'message' => 'El vehículo ha sido eliminado de tu listado']);
        } else {
            return response()->json(['success' => false, 'message' => 'El vehículo no pudo ser eliminado de tu listado']);
        }
    }
}

resources/views/vehicles/create.blade.php
@extends('layouts.app')

@section('content')

	<h3>Agregar Vehiculo</h3>

	{!! Form::open(['route' => 'mis-vehiculos.store', 'method' => 'POST', 'role' => 'form']) !!}
		<div class="form-group">
			{!! Form::text('plate', '', ['class' => 'form-control', 'placeholder' => 'Chapa', 'required' => true] )!!}

			@if ($errors->has('plate'))
	        <span class="help-block">
	            <strong>{{ $errors->first('plate') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('brand', '', ['class' => 'form-control', 'placeholder' => 'Marca', 'required' => true] )!!}
			@if ($errors->has('brand'))
	        <span class="help-block">
	            <strong>{{ $errors->first('brand') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('color', '', ['class' => 'form-control', 'placeholder' => 'Color', 'required' => true] )!!}
			@if ($errors->has('color'))
	        <span class="help-block">
	            <strong>{{ $errors->first('color') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('model', '', ['class' => 'form-control', 'placeholder' => 'Modelo', 'required' => true] )!!}
			@if ($errors->has('model'))
	        <span class="help-block">
	            <strong>{{ $errors->first('model') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('chassis', '', ['class' => 'form-control', 'placeholder' => 'Chasis'] )!!}
			@if ($errors->has('chassis'))
	        <span class="help-block">
	            <strong>{{ $errors->first('chassis') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('document', '', ['class' => 'form-control', 'placeholder' => 'Cédula Verde', 'required' => true] )!!}
			@if ($errors->has('document'))
	        <span class="help-block">
	            <strong>{{ $errors->first('document') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::select('status', [1 => 'Activo', 2=> 'Inactivo'], 1, ['class' => 'form-control']) !!}
			@if ($errors->has('status'))
	        <span class="help-block">
	            <strong>{{ $errors->first('status') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::submit('Guardar', ['class' => 'btn btn-success'] )!!}
			<a href="{{ route('multas.index')}}" class="btn btn-danger pull-right">Cancelar</a>
		</div>

	{!! Form::close() !!}

@endsection

resources/views/vehicles/edit.blade.php
@extends('layouts.app')

@section('content')

	<h3>Editar Vehiculo</h3>

	{!! Form::open(['route' => ['mis-vehiculos.update', $vehicle->id], 'method' => 'PUT', 'role' => 'form']) !!}
		<div class="form-group">
			{!! Form::text('plate', $vehicle->plate, ['class' => 'form-control', 'placeholder' => 'Chapa', 'required' => true] )!!}

			@if ($errors->has('plate'))
	        <span class="help-block">
	            <strong>{{ $errors->first('plate') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('brand', $vehicle->brand, ['class' => 'form-control', 'placeholder' => 'Marca', 'required' => true] )!!}
			@if ($errors->has('brand'))
	        <span class="help-block">
	            <strong>{{ $errors->first('brand') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('color', $vehicle->color, ['class' => 'form-control', 'placeholder' => 'Color', 'required' => true] )!!}
			@if ($errors->has('color'))
	        <span class="help-block">
	            <strong>{{ $errors->first('color') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('model', $vehicle->model, ['class' => 'form-control', 'placeholder' => 'Modelo', 'required' => true] )!!}
			@if ($errors->has('model'))
	        <span class="help-block">
	            <strong>{{ $errors->first('model') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('chassis', $vehicle->chassis, ['class' => 'form-control', 'placeholder' => 'Chasis'] )!!}
			@if ($errors->has('chassis'))
	        <span class="help-block">
	            <strong>{{ $errors->first('chassis') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::text('document', $vehicle->document, ['class' => 'form-control', 'placeholder' => 'Cédula Verde', 'required' => true] )!!}
			@if ($errors->has('document'))
	        <span class="help-block">
	            <strong>{{ $errors->first('document') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::select('status', [1 => 'Activo', 2=> 'Inactivo'], $vehicle->status, ['class' => 'form-control']) !!}
			@if ($errors->has('status'))
	        <span class="help-block">
	            <strong>{{ $errors->first('status') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			{!! Form::submit('Guardar', ['class' => 'btn btn-success'] )!!}
			<a href="{{ route('multas.index')}}" class="btn btn-danger pull-right">Cancelar</a>
		</div>

	{!! Form::close() !!}

@endsection

resources/views/vehicles/index.blade.php
@extends('layouts.app')

@section('content')

	<h3>Mis Vehículos</h3>

	<a href="{{ route('mis-vehiculos.create')}}" class="btn btn-success">Agregar Vehículo</a>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Chapa</th>
				<th>Marca</th>
				<th>Color</th>
				<th>Modelo</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			@foreach ($vehicles as $vehicle)
				<tr data-id="{{ $vehicle->id }}">
					<td>{{ $vehicle->plate }}</td>
					<td>{{ $vehicle->brand }}</td>
					<td>{{ $vehicle->color }}</td>
					<td>{{ $vehicle->model }}</td>
					<td>
						<a href="{{ route('mis-vehiculos.edit', $vehicle->id)}}">Editar</a>
						<a href="#" class="btn-remove">Eliminar</a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>

	{!! $vehicles->links() !!}

	{!! Form::open(['route' => ['mis-vehiculos.destroy',':ROW_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
	{!! Form::close() !!}

@endsection

@section('scripts')
<script type="text/javascript">
	$(function() {
		$('.btn-remove').click(function(e){
			e.preventDefault();
			var row = $(this).parents('tr');
			var id = row.data('id');
			swal({
			  title: "Estas seguro de eliminar el vehículo?",
			  text: "Con esta acción los datos no podrán ser recuperados!",
			  type: "warning",
			  showCancelButton: true,
			  confirmButtonColor: "#DD6B55",
			  confirmButtonText: "Eliminar!",
			  cancelButtonText: "Cancelar!"
			}).then(function(isConfirm){
				console.log(isConfirm);
			  if (isConfirm) {
				var form = $('#form-delete');
				var url = form.attr('action').replace(':ROW_ID',id);
				var data = form.serialize();
				var type = "";
				var title = "";
			  	$.post(url,data, function(result){
					if(result.success){
						row.fadeOut();
						type = "success";
						title = "Operación realizada!";
					}else{
						type = "error";
						title =  "No se pudo realizar la operación";
					}
					swal({   title: title,   text: result.message,   type: type,   confirmButtonText: "Aceptar" });
				}).fail(function (){
					swal('No se pudo realizar la petición.');
				});
			  } else {
			    swal("Cancelado", "El vehículo no ha sido eliminado", "error");
			  }
			});
		});
	});
</script>
@endsection