routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => ['bloqued']], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index');
	Route::get('/perfil', 'UserController@account')->name('account');
	Route::put('/perfil', 'UserController@updateAccount')->name('update_account');
	Route::get('/comprar-minutos', 'TicketController@time')->name('time');
	Route::post('/comprar-minutos', 'TicketController@buyTime')->name('buy_time');
	Route::get('/cargar-billetera', 'TicketController@showWallet')->name('wallet');
	Route::post('/cargar-billetera', 'TicketController@buyWallet')->name('buy_wallet');
	Route::get('/comprar-ticket', 'TicketController@tickets')->name('tickets');
	Route::post('/comprar-ticket', 'TicketController@buyTicket')->name('buy_tickets');
	Route::resource('/mis-vehiculos', 'VehicleController');


	Route::group(['middleware' => ['role:admin,pmt'] ], function(){
		Route::resource('multas', 'PenaltyController');
	});

	Route::group(['middleware' => 'role:admin'], function(){
		Route::resource('zonas', 'ZoneController');
		Route::resource('usuarios', 'UserController');
		Route::resource('planes', 'PlanController');
		Route::resource('metodos', 'PaymentMethodController');
	});
});

app/Plan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    protected $fillable = ['description', 'minutes', 'amount', 'status'];
}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Plan;

class PlanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $plans = Plan::paginate(15);
        return view('plans.index', ['plans' => $plans]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('plans.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'description' => 'string|required|max:255|unique:plans',
            'minutes'     => 'integer|required|min:0',
            'amount'      => 'integer|required|min:0',
            'status'      => 'boolean'
        ]);

        $plan = Plan::create($request->only(['description', 'minutes', 'amount', 'status']));

        if($plan){
            flash('El plan ha sido creado!')->success();
            return redirect()->route('planes.index');
        } else {
            flash('El plan no pudo ser creado')->danger();
            return redirect()->route('planes.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/plans/create.blade.php
@extends('layouts.app')

@section('content')

	<h3>Agregar Plan</h3>

	{!! Form::open(['route' => 'planes.store', 'method' => 'POST', 'role' => 'form']) !!}
		<div class="form-group">
			{!! Form::text('description', '', ['class' => 'form-control', 'placeholder' => 'Descripción'] )!!}

			@if ($errors->has('description'))
	        <span class="help-block">
	            <strong>{{ $errors->first('description') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			<label for="minutes">Minutos</label>
			{!! Form::number('minutes', 0, ['class' => 'form-control', 'placeholder' => 'Minutos', 'id' => 'minutes'] )!!}
			@if ($errors->has('minutes'))
	        <span class="help-block">
	            <strong>{{ $errors->first('minutes') }}</strong>
	        </span>
	    	@endif
		</div>

		<div class="form-group">
			<label for="amount">Monto</label>
			{!! Form::number('amount', 0, ['class' => 'form-control', 'placeholder' => 'Monto', 'id' => 'amount'] )!!}
			@if ($errors->has('amount'))
	        <span class="help-block">
	            <strong>{{ $errors->first('amount') }}</strong>
	        </span>
	        @endif
		</div>

		<div class="form-group">
			<label for="status">Estado</label>
			{!! Form::select('status', [true => 'Activo', false => 'Inactivo'], true, ['class' => 'form-control', 'id' => 'status'] )!!}
			@if ($errors->has('status'))
	        <span class="help-block">
	            <strong>{{ $errors->first('status') }}</strong>
	        </span>
	        @endif
		</div>

		<div class="form-group">
			{!! Form::submit('Guardar', ['class' => 'btn btn-success'] )!!}
			<a href="{{ route('planes.index')}}" class="btn btn-danger pull-right">Cancelar</a>
		</div>

	{!! Form::close() !!}

@endsection

resources/views/plans/index.blade.php
@extends('layouts.app')

@section('content')

	<h3>Planes</h3>

	<a href="{{ route('planes.create')}}" class="btn btn-success">Agregar Plan</a>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Descripcion</th>
				<th>Monto</th>
				<th>Minutos</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			@foreach ($plans as $plan)
				<tr data-id="{{ $plan->id }}">
					<td>{{ $plan->description }}</td>
					<td>{{ $plan->amount }}</td>
					<td>{{ $plan->minutes }}</td>
					<td>
						<a href="{{ route('planes.edit', $plan->id)}}">Editar</a>
						<a href="#" class="btn-remove">Eliminar</a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>

	{!! $plans->links() !!}

	{!! Form::open(['route' => ['planes.destroy',':ROW_ID'], 'method' => 'DELETE', 'id' => 'form-delete']) !!}
	{!! Form::close() !!}

@endsection

@section('scripts')
<script type="text/javascript">
	$(function() {
		$('.btn-remove').click(function(e){
			e.preventDefault();
			var row = $(this).parents('tr');
			var id = row.data('id');
			swal({
			  title: "Estas seguro de eliminar el plan?",
			  text: "Con esta acción los datos no podrán ser recuperados!",
			  type: "warning",
			  showCancelButton: true,
			  confirmButtonColor: "#DD6B55",
			  confirmButtonText: "Eliminar!",
			  cancelButtonText: "Cancelar!"
			}).then(function(isConfirm){
				console.log(isConfirm);
			  if (isConfirm) {
				var form = $('#form-delete');
				var url = form.attr('action').replace(':ROW_ID',id);
				var data = form.serialize();
				var type = "";
				var title = "";
			  	$.post(url,data, function(result){
					if(result.success){
						row.fadeOut();
						type = "success";
						title = "Operación realizada!";
					}else{
						type = "error";
						title =  "No se pudo realizar la operación";
					}
					swal({   title: title,   text: result.message,   type: type,   confirmButtonText: "Aceptar" });
				}).fail(function (){
					swal('No se pudo realizar la petición.');
				});
			  } else {
			    swal("Cancelado", "El plan no ha sido eliminado", "error");
			  }
			});
		});
	});
</script>
@endsection